# Generated by Django 5.2.12 on 2026-04-10 09:15

import django.core.validators
import posts.models.post
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_alter_like_unique_together_post_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="post_images/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp"]
                    ),
                    posts.models.post.validate_post_image_size,
                ],
            ),
        ),
    ]
