services:
  db:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=antisocial_dev
      - POSTGRES_PASSWORD=antisocial_dev
      - POSTGRES_DB=antisocial_dev_db
      - POSTGRES_HOST_AUTH_METHOD=md5
    networks:
      - antisocial_network
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - media_data:/app/media
    ports:
      - 8000:8000
    env_file:
      - ./env.dev
    networks:
      - antisocial_network
      - frontend
    depends_on:
      - db
networks:
  antisocial_network:
    driver: bridge
  frontend:
    driver: bridge
volumes:
  postgres_data:
  media_data:
